# Generated by Django 4.2.5 on 2023-10-16 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_dislikes_post_likes_like_dislike_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='post',
        ),
        migrations.RemoveField(
            model_name='dislike',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
